spring:
  application:
    name: promeditor

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.ddoongddak.promeditor.config.UpperCaseNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

logging:
  level:
    com.ddoongddak.promeditor: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
