-- Promeditor 초기 스키마
-- Phase 1: TEMPLATES, TEMPLATE_BLOCKS, SLOT_OPTIONS

CREATE TABLE IF NOT EXISTS TEMPLATES (
    ID          BIGSERIAL       NOT NULL,
    TITLE       VARCHAR(100)    NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT  TIMESTAMP       NOT NULL,
    UPDATED_AT  TIMESTAMP       NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TEMPLATE_BLOCKS (
    ID          BIGSERIAL       NOT NULL,
    TEMPLATE_ID BIGINT          NOT NULL,
    BLOCK_TYPE  VARCHAR(10)     NOT NULL,   -- FIXED / SLOT
    CONTENT     TEXT,                       -- FIXED: 텍스트 내용 / SLOT: 슬롯 이름
    SLOT_TYPE   VARCHAR(10),                -- TEXT / TEXTAREA / SELECT (SLOT일 때만)
    SORT_ORDER  INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    CONSTRAINT FK_BLOCK_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES TEMPLATES (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SLOT_OPTIONS (
    ID          BIGSERIAL       NOT NULL,
    BLOCK_ID    BIGINT          NOT NULL,
    LABEL       VARCHAR(100)    NOT NULL,
    SORT_ORDER  INT             NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    CONSTRAINT FK_OPTION_BLOCK FOREIGN KEY (BLOCK_ID)
        REFERENCES TEMPLATE_BLOCKS (ID) ON DELETE CASCADE
);
