-- Phase 4: 카테고리, 즐겨찾기, 태그 추가

ALTER TABLE TEMPLATES ADD COLUMN IF NOT EXISTS CATEGORY    VARCHAR(50);
ALTER TABLE TEMPLATES ADD COLUMN IF NOT EXISTS IS_FAVORITE BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS TEMPLATE_TAGS (
    ID          BIGSERIAL    NOT NULL,
    TEMPLATE_ID BIGINT       NOT NULL,
    TAG         VARCHAR(50)  NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_TAG_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES TEMPLATES (ID) ON DELETE CASCADE
);
