-- Phase 5: 입력값 히스토리

CREATE TABLE IF NOT EXISTS TEMPLATE_HISTORIES (
    ID          BIGSERIAL    NOT NULL,
    TEMPLATE_ID BIGINT       NOT NULL,
    SLOT_VALUES TEXT         NOT NULL,   -- JSON {"슬롯이름": "입력값", ...}
    CREATED_AT  TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_HISTORY_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
        REFERENCES TEMPLATES (ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_HISTORY_TEMPLATE_ID ON TEMPLATE_HISTORIES (TEMPLATE_ID, CREATED_AT DESC);
